name: EAS Build Preview (develop)

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build APK Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build APK Preview
        run: eas build --profile preview --platform android --non-interactive
